#!/usr/bin/env bash
# One-shot: Nginx 反代 DeepGraph + Certbot 签发 Let's Encrypt 证书。
# 需要 root（sudo）。用法：
#   sudo bash /home/billion-token/Deepgraph/scripts/install-https-nginx.sh
# 可选：CERTBOT_EMAIL=you@example.com（否则使用 --register-unsafely-without-email）

set -euo pipefail

DOMAIN="deepgraph.sora2.today"
UPSTREAM="127.0.0.1:8080"
NGINX_CONF="/etc/nginx/conf.d/deepgraph.conf"

if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
	echo "请使用 root 运行: sudo bash $0" >&2
	exit 1
fi

dnf install -y nginx python3-certbot-nginx

cat >"$NGINX_CONF" <<EOF
# DeepGraph dashboard — generated by install-https-nginx.sh
server {
	listen 80;
	listen [::]:80;
	server_name ${DOMAIN};

	location / {
		proxy_pass http://${UPSTREAM};
		proxy_http_version 1.1;
		proxy_set_header Host \$host;
		proxy_set_header X-Real-IP \$remote_addr;
		proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto \$scheme;
		proxy_read_timeout 86400;
	}
}
EOF

nginx -t
systemctl enable --now nginx

CERTBOT_EMAIL="${CERTBOT_EMAIL:-}"
CERTBOT_EXTRA=()
if [[ -n "${CERTBOT_EMAIL}" ]]; then
	CERTBOT_EXTRA=(--email "${CERTBOT_EMAIL}")
else
	CERTBOT_EXTRA=(--register-unsafely-without-email)
fi

certbot --nginx \
	-d "${DOMAIN}" \
	--non-interactive \
	--agree-tos \
	"${CERTBOT_EXTRA[@]}" \
	--redirect

echo "完成: https://${DOMAIN} 应已指向本机 Nginx → ${UPSTREAM}"
echo "请确认 AWS 安全组已放行 TCP 80、443 入站；DeepGraph 需在 ${UPSTREAM} 监听。"
